#!/usr/bin/env python3
"""
UltimateEPG XMLTV builder.

Reads config/channels.csv, downloads the mapped public XMLTV feeds,
extracts only the requested channel IDs, and publishes one merged XMLTV file.

The builder intentionally does NOT fabricate programme data. A channel is
included only when its source feed contains the exact mapped EPG ID.
"""

from __future__ import annotations

import csv
import gzip
import io
import json
import os
import shutil
import sys
import tempfile
import time
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config" / "channels.csv"
SITE = ROOT / "site"
XML_OUT = SITE / "UltimateEPG.xml"
STATUS_OUT = SITE / "status.json"
USER_AGENT = "UltimateEPG/1.0 XMLTV builder"
TIMEOUT = 120
RETRIES = 3

def tag_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]

def load_mapping():
    with CONFIG.open("r", encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
    rows = [r for r in rows if r.get("include", "").strip().lower() in ("true", "1", "yes")]
    if not rows:
        raise RuntimeError("No included channels found in config/channels.csv")
    return rows

def download(url: str, destination: Path):
    last = None
    for attempt in range(1, RETRIES + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp, destination.open("wb") as out:
                shutil.copyfileobj(resp, out)
            if destination.stat().st_size == 0:
                raise RuntimeError("downloaded file is empty")
            return
        except Exception as exc:
            last = exc
            if attempt < RETRIES:
                time.sleep(3 * attempt)
    raise RuntimeError(f"Failed to download {url}: {last}")

def open_xml_file(path: Path, url: str):
    # Prefer gzip when URL indicates .gz, but also auto-detect gzip magic bytes.
    raw = path.open("rb")
    head = raw.read(2)
    raw.seek(0)
    if url.lower().endswith(".gz") or head == b"\x1f\x8b":
        return gzip.GzipFile(fileobj=raw, mode="rb")
    return raw

def parse_source(url: str, target_ids: set[str], workdir: Path):
    downloaded = workdir / ("feed_" + str(abs(hash(url))) + ".dat")
    download(url, downloaded)

    channels = {}
    programme_file = workdir / ("programmes_" + str(abs(hash(url))) + ".xmlparts")
    programme_count = defaultdict(int)

    # Write selected programme fragments to disk, keeping memory bounded.
    with programme_file.open("wb") as pf:
        source = open_xml_file(downloaded, url)
        try:
            context = ET.iterparse(source, events=("end",))
            for _, elem in context:
                t = tag_name(elem.tag)
                if t == "channel":
                    cid = elem.attrib.get("id", "")
                    if cid in target_ids:
                        channels[cid] = ET.tostring(elem, encoding="utf-8")
                    elem.clear()
                elif t == "programme":
                    cid = elem.attrib.get("channel", "")
                    if cid in target_ids:
                        pf.write(ET.tostring(elem, encoding="utf-8"))
                        pf.write(b"\n")
                        programme_count[cid] += 1
                    elem.clear()
        finally:
            source.close()

    return channels, programme_file, programme_count

def write_xml(mapping, source_results, generated_at):
    SITE.mkdir(parents=True, exist_ok=True)

    # Only publish channels for which the source supplied the exact channel ID.
    selected = {}
    programmes = []
    counts = {}

    for url, result in source_results.items():
        channels, programme_file, pcounts = result
        selected.update(channels)
        counts.update(pcounts)
        if programme_file.exists():
            programmes.append(programme_file)

    # Keep a stable order based on config.
    ordered_ids = []
    seen = set()
    for row in mapping:
        cid = row["epg_id"]
        if cid in selected and cid not in seen:
            ordered_ids.append(cid)
            seen.add(cid)

    tmp = XML_OUT.with_suffix(".xml.tmp")
    with tmp.open("wb") as out:
        out.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
        out.write(f'<!-- Generated by UltimateEPG at {generated_at} -->\n'.encode("utf-8"))
        out.write(b"<tv generator-info-name=\"UltimateEPG\" generator-info-url=\"https://github.com/SPSteenkamp/UltimateEPG\">\n")
        for cid in ordered_ids:
            out.write(selected[cid])
            out.write(b"\n")

        # Programme fragments are already filtered by channel ID.
        for pf in programmes:
            with pf.open("rb") as f:
                shutil.copyfileobj(f, out)

        out.write(b"</tv>\n")

    tmp.replace(XML_OUT)
    return ordered_ids, counts

def main():
    mapping = load_mapping()
    by_source = defaultdict(set)
    for row in mapping:
        if row.get("epg_source_url") and row.get("epg_id"):
            by_source[row["epg_source_url"]].add(row["epg_id"])

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source_results = {}
    source_status = {}

    with tempfile.TemporaryDirectory() as td:
        workdir = Path(td)
        for url, ids in by_source.items():
            try:
                result = parse_source(url, ids, workdir)
                source_results[url] = result
                channels, _, pcounts = result
                source_status[url] = {
                    "status": "ok",
                    "requested_channels": len(ids),
                    "matched_channels": len(channels),
                    "channels_with_programmes": sum(1 for cid in channels if pcounts.get(cid, 0) > 0),
                    "programme_records": sum(pcounts.values()),
                }
            except Exception as exc:
                source_status[url] = {
                    "status": "failed",
                    "requested_channels": len(ids),
                    "error": str(exc),
                }

        matched_ids, programme_counts = write_xml(mapping, source_results, generated_at)

    missing_channels = []
    no_programmes = []
    for row in mapping:
        cid = row["epg_id"]
        if cid not in matched_ids:
            missing_channels.append({
                "epg_id": cid,
                "channel": row["canonical_channel_name"],
                "country": row["country"],
                "source": row["epg_source_url"],
            })
        elif programme_counts.get(cid, 0) == 0:
            no_programmes.append({
                "epg_id": cid,
                "channel": row["canonical_channel_name"],
                "country": row["country"],
            })

    status = {
        "generated_at_utc": generated_at,
        "requested_mappings": len(mapping),
        "published_channels": len(matched_ids),
        "channels_missing_from_source": len(missing_channels),
        "channels_without_programmes": len(no_programmes),
        "programme_records": sum(programme_counts.values()),
        "sources": source_status,
        "missing_channels": missing_channels,
        "channels_without_programmes": no_programmes,
        "xmltv_url": "https://spsteenkamp.github.io/UltimateEPG/UltimateEPG.xml",
    }

    STATUS_OUT.write_text(json.dumps(status, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Do not publish an empty/broken EPG.
    if not matched_ids:
        raise RuntimeError("No mapped channels were found in any source feed.")
    if sum(programme_counts.values()) == 0:
        raise RuntimeError("No programme records were found. Refusing to publish an empty EPG.")

    print(json.dumps({
        "requested_mappings": len(mapping),
        "published_channels": len(matched_ids),
        "missing_channels": len(missing_channels),
        "programme_records": sum(programme_counts.values()),
    }, indent=2))

if __name__ == "__main__":
    main()
